Добавляет разметку главной страницы
htmlacademy-htmlcss/1913865-device-32 pull request #2
Opened 2021-10-03 00:44 UTC by danyiimp

2021-10-03 15:44 UTC, baileys-li requested changes
Хорошая работа. Пока не хватает понимание какие элементы можно вкладывать друг в друга, а какие нет

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +      <section class="gallery">
Я пока не решил, как лучше разметить этот слайдер, но точно могу сказать, что лучше выделить пагинацию в отдельный блок и описание товаров
```html
        <ol class="slider-pagination">
          <li class="slider-pagination-item">
            <button class="slider-pagination-button" type="button" aria-selected="true">
              <span class="visually-hidden">Промо товар</span>
            </button>
          </li>
          <li class="slider-pagination-item">
            <button class="slider-pagination-button" type="button">
              <span class="visually-hidden">Промо товар</span>
            </button>
          </li>
          <li class="slider-pagination-item">
            <button class="slider-pagination-button" type="button">
              <span class="visually-hidden">Промо товар</span>
            </button>
          </li>
        </ol>
```

Это точки которые всегда сбоку. О писание товаров перенеси в отдельный `ol`, поскольку они будут меняться

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +              </b>
```suggestion
              <strong class="slider-description-title">
                Порхает как бабочка, жалит как пчела!
              </strong >
```

На этих "подзаголовков" делается прям смысловой акцент, поэтому `strong` больше подходит. `br` пока лучше не растравлять

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +            <table class="slider-table">
таблицу нельзя вкладывать в параграф

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +              </tr>
1. Не надо заниматься стилизацией тэгом `b`. Стилизацией вы занимаетесь потом2
2. Думай про семантику. Обычно название категорий в шапке таблицы
3. То что категории сверху пока не обращай внимание, как и то что они полужирным шрифтом

Взял для примера самую маленькую таблицу, для остальных тоже самое
```suggestion
              <thead>
                <tr class="slider-table-row">
                  <th class="slider-table-cell-title">Без подзарядки<th>
                </tr>
              </thead>
              <tbody>
                <tr class="slider-table-row">
                  <td class="slider-table-cell-info">48 часов</td>
                </tr>
              </tbody>
```

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +            <h3 class="categories-name">Виртуальная реальность</h3>
Поскольку в стайлгайде для заголовка и картинки одни и те же состояние, значит они обёрнуты в одну ссылку. 
```suggestion
            <a class="categories-link" href="#">
              <img src="" alt="Очки виртуальной реальности">
              <h3 class="categories-name">Виртуальная реальность</h3>
            </a>        
```

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +          </li>
Опять таки. Лучше сделать отдельно навигацией с ссылками, а потом секции которые показывают текст.

Например как [здесь](https://web-standards.ru/articles/tabbed-interfaces/)

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +      </aside>
Это всё одна ссылка. А поскольку для информации нет состояний в стайлгайде, её сейчас реализовывать не нужно

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +            </b>
Так, для простоты удаляем все `b` в документе 😂

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +            </b>
Необязательно, просто ставлю в курс о не самом известном тэге
```suggestion
            <abbr title="Служба доставки Икспресс-Курьер">
              СДИК
            </abbr>
```

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +        <address class="contacts-address">
Ого, `address`. Уважаю

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +            <a class="contacts-number-link" href="tel:+78128121212">Тел.: +7 (812) 812-12-12</a>
«Тел» нет в макете

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +          </label>
Нет смысла плодить сущности
```suggestion
          <label for="subscribe-email" class="visually-hidden">
              E-mail
          </label>
```

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +          </label>
А ещё можно засунуть лейблы в уже существующий текс

```html
<h2 class="subscribe-title">
  <label for="subscribe-email">Подпишитесь на рассылку</label>
</h2>
```

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +          <input type="text" name="subscribe-email" id="subscribe-email" placeholder="Ваш e-mail">
```suggestion
          <input type="email" name="subscribe-email" id="subscribe-email" placeholder="Ваш e-mail">
```

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +        </p>
уже писал что не так

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +          <u class="footer-social-list">
```suggestion
          <ul class="footer-social-list">
```

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +          <u class="footer-social-list">
Можно ли засовывать список в `p`?

Ну думаю догадаешься или сам найдёшь 😂

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +      <nav class="footer-navigation">
Лучше не нужно вставлять навигацию и заголовки в футер.

2021-10-03 15:44 UTC, baileys-li commented on index.html
> +        </p>
С тз в макете
> Логотип и текст .html academy ведут на главную страницу сайта разработчика — https://htmlacademy.ru/

2021-10-04 13:21 UTC, danyiimp commented on index.html
> +      </p>
Мне нужно давать класс h1 в этом случае ?

2021-10-04 14:49 UTC, danyiimp commented on index.html
> +              </tr>
На 125 у вас th не закрыт, если я правильно понимаю?

2021-10-04 14:59 UTC, baileys-li commented on index.html
> +      </p>
@danyiimp Если понадобиться для стилизации, да (а скорее понадобиться чтобы дефолтные марджины обнулить)

Так можно по критериям можно через родитель `.page-header h1`

Я пока классы везде не проверяю, да и ставил бы их по надобности

2021-10-05 10:14 UTC, baileys-li commented on index.html
>          </ul>
Тут заголовки не нужны. Смущают
![image](https://user-images.githubusercontent.com/47776594/136004323-ddb11cc6-f830-45a3-adf1-fc4148beb038.png)

2021-10-05 10:17 UTC, baileys-li commented on index.html
> +            <a class="services-link" href="#credit"><h3 class="services-name">Кредит</h3></a>
Тут заголовки не нужны. Смущают
![image](https://user-images.githubusercontent.com/47776594/136004323-ddb11cc6-f830-45a3-adf1-fc4148beb038.png)

2021-10-05 10:21 UTC, baileys-li commented on index.html
> +              </tr>
Не вижу, но я мне и неудобно писать в комментах

2021-10-05 10:25 UTC, merged